sudo: required
language: generic
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker build -t $REPO --build-arg COMMIT=${TRAVIS_COMMIT} .
after_success:
  - docker --version
  - docker tag $REPO
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:latest
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO
