sudo: required
language: generic
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker build -t $REPO --build-arg COMMIT=${COMMIT} .
after_success:
  - docker --version
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:git-$COMMIT
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $REPO
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
